FROM node:latest as node
RUN mkdir -p /app
WORKDIR /app
COPY . /app/
WORKDIR /app/frontend
RUN npm install 
CMD ["npm", "run", "dev"]
WORKDIR /app/backend
RUN npm install
CMD ["npm", "run", "start"]
EXPOSE 3000
EXPOSE 5000